---
services:
  gotify:
    container_name: gotify
    image: gotify/server
    ports:
      - 8080:80
    environment:
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=${ADMIN_PASSWORD}
    volumes:
      - "./gotify_data:/app/data"
    restart: unless-stopped
