services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
       - "1883:1883"
       - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/pwfile:/mosquitto/config/pwfile
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    security_opt:
      - no-new-privileges:true
