services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Lisbon
    restart: unless-stopped
    ports:
     - 8123:8123
    networks:
      home-assistant:
    depends_on:
      - homeassistant-db
    security_opt:
      - no-new-privileges:true


  homeassistant-db:
    image: docker.io/postgres:16.3
    container_name: homeassistant-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=HA-DB-user
      - POSTGRES_PASSWORD=${HA_DB_PASSWORD}
      - POSTGRES_DB=homeassistant-db
      # ensure the database gets created correctly
      # https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - ./schemas:/var/lib/postgresql/data
    networks:
      home-assistant:
    security_opt:
      - no-new-privileges:true

networks:
  home-assistant:
