# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Add this to make automations show up in UI
automation: !include automations.yaml

recorder:
  # NOTE: must match the homeassistant-db credentials in docker-compose.yml
  db_url: postgresql://HA-DB-user:{HA_BD_PASSWORD}@homeassistant-db/homeassistant-db
